name: Project Release

on:
  push:
    tags:
      - "v*.*.*" # Runs only when tagging a version like v1.0.0

jobs:
  use-release:
    uses: Gitdigital-products/.github/.github/workflows/release.yml@main
    with:
      node_version: "20"